function setup() {
  createCanvas(1000, 1000);
}

function draw() {
  // background (RGB)
  //range of value (0-255);
  background(0, 0, 0 );
   //ellipse( x point, y point, width, height)
    fill(0, 59, 0);
    strokeWeight(05);
    stroke(0, 0, 5);
    ellipse(500, 400, 100, 100);

      fill(0, 59, 0);// color in RGB
      strokeWeight(0); //thickness in pixels
    stroke(255); //white color for outline
    rect(mouseX, mouseY, 50, 50);

      fill(0, 59, 0);
      stroke(255, 255, 0);
      textSize(20);
      textFont("Courier New");
      text("New Virus Detected!", 50, 50);
        fill(0, 59, 0);
        stroke(255, 255, 0);
        textSize(20);
        textFont("Courier New");
        text("New Virus Detected!", 50, 75);
          fill(0, 59, 0);
          stroke(255, 255, 0);
          textSize(20);
          textFont("Courier New");
          text("New Virus Detected!", 50, 100);
            fill(0, 59, 0);
            stroke(255, 255, 0);
            textSize(20);
            textFont("Courier New");
            text("New Virus Detected!", 50, 125);
              fill(0, 59, 0);
              stroke(255, 255, 0);
              textSize(20);
              textFont("Courier New");
              text("New Virus Detected!", 50, 150);
                fill(0, 59, 0);
                stroke(255, 255, 0);
                textSize(20);
                textFont("Courier New");
                text("New Virus Detected!", 50, 175);
                  fill(0, 59, 0);
                  stroke(255, 255, 0);
                  textSize(20);
                  textFont("Courier New");
                  text("New Virus Detected!", 50, 200);
                    fill(0, 59, 0);
                    stroke(255, 255, 0);
                    textSize(20);
                    textFont("Courier New");
                    text("New Virus Detected!", 50, 225);
                      fill(0, 59, 0);
                      stroke(255, 255, 0);
                      textSize(20);
                      textFont("Courier New");
                      text("New Virus Detected!", 50, 250);
                        fill(0, 59, 0);
                        stroke(255, 255, 0);
                        textSize(20);
                        textFont("Courier New");
                        text("New Virus Detected!", 50, 275);
                          fill(0, 59, 0);
                          stroke(255, 255, 0);
                          textSize(20);
                          textFont("Courier New");
                          text("New Virus Detected!", 50, 300);
                            fill(0, 59, 0);
                            stroke(255, 255, 0);
                            textSize(20);
                            textFont("Courier New");
                            text("New Virus Detected!", 50, 325);
                              fill(0, 59, 0);
                              stroke(255, 255, 0);
                              textSize(20);
                              textFont("Courier New");
                              text("New Virus Detected!", 50, 350);
                                fill(0, 59, 0);
                                stroke(255, 255, 0);
                                textSize(20);
                                textFont("Courier New");
                                text("New Virus Detected!", 50, 375);
                                  fill(0, 59, 0);
                                  stroke(255, 255, 0);
                                  textSize(20);
                                  textFont("Courier New");
                                  text("New Virus Detected!", 50, 400);
                                    fill(0, 59, 0);
                                    stroke(255, 255, 0);
                                    textSize(20);
                                    textFont("Courier New");
                                    text("New Virus Detected!", 50, 425);
                                      fill(0, 59, 0);
                                      stroke(255, 255, 0);
                                      textSize(20);
                                      textFont("Courier New");
                                      text("New Virus Detected!", 50, 450);
                                        fill(0, 59, 0);
                                        stroke(255, 255, 0);
                                        textSize(20);
                                        textFont("Courier New");
                                        text("New Virus Detected!", 50, 475);
                                        //18 PER ROW//

    fill(0, 59, 0);
    stroke(255, 255, 0);
    textSize(20);
    textFont("Courier New");
    text("New Virus Detected!", 280, 50);
      fill(0, 59, 0);
      stroke(255, 255, 0);
      textSize(20);
      textFont("Courier New");
      text("New Virus Detected!", 280, 75);
        fill(0, 59, 0);
        stroke(255, 255, 0);
        textSize(20);
        textFont("Courier New");
        text("New Virus Detected!", 280, 100);
          fill(0, 59, 0);
          stroke(255, 255, 0);
          textSize(20);
          textFont("Courier New");
          text("New Virus Detected!", 280, 125);
            fill(0, 59, 0);
            stroke(255, 255, 0);
            textSize(20);
            textFont("Courier New");
            text("New Virus Detected!", 280, 150);
              fill(0, 59, 0);
              stroke(255, 255, 0);
              textSize(20);
              textFont("Courier New");
              text("New Virus Detected!", 280, 175);
                fill(0, 59, 0);
                stroke(255, 255, 0);
                textSize(20);
                textFont("Courier New");
                text("New Virus Detected!", 280, 200);
                  fill(0, 59, 0);
                  stroke(255, 255, 0);
                  textSize(20);
                  textFont("Courier New");
                  text("New Virus Detected!", 280, 225);
                    fill(0, 59, 0);
                    stroke(255, 255, 0);
                    textSize(20);
                    textFont("Courier New");
                    text("New Virus Detected!", 280, 250);
                      fill(0, 59, 0);
                      stroke(255, 255, 0);
                      textSize(20);
                      textFont("Courier New");
                      text("New Virus Detected!", 280, 275);
                        fill(0, 59, 0);
                        stroke(255, 255, 0);
                        textSize(20);
                        textFont("Courier New");
                        text("New Virus Detected!", 280, 200);
//
fill(0, 59, 0);
stroke(255, 255, 0);
textSize(20);
textFont("Courier New");
text("New Virus Detected!", 510, 50);
  fill(0, 59, 0);
  stroke(255, 255, 0);
  textSize(20);
  textFont("Courier New");
  text("New Virus Detected!", 510, 75);
    fill(0, 59, 0);
    stroke(255, 255, 0);
    textSize(20);
    textFont("Courier New");
    text("New Virus Detected!", 510, 100);
      fill(0, 59, 0);
      stroke(255, 255, 0);
      textSize(20);
      textFont("Courier New");
      text("New Virus Detected!", 510, 125);
        fill(0, 59, 0);
        stroke(255, 255, 0);
        textSize(20);
        textFont("Courier New");
        text("New Virus Detected!", 510, 150);
          fill(0, 59, 0);
          stroke(255, 255, 0);
          textSize(20);
          textFont("Courier New");
          text("New Virus Detected!", 510, 175);
            fill(0, 59, 0);
            stroke(255, 255, 0);
            textSize(20);
            textFont("Courier New");
            text("New Virus Detected!", 510, 200);
              fill(0, 59, 0);
              stroke(255, 255, 0);
              textSize(20);
              textFont("Courier New");
              text("New Virus Detected!", 510, 225);
                fill(0, 59, 0);
                stroke(255, 255, 0);
                textSize(20);
                textFont("Courier New");
                text("New Virus Detected!", 510, 250);
                  fill(0, 59, 0);
                  stroke(255, 255, 0);
                  textSize(20);
                  textFont("Courier New");
                  text("New Virus Detected!", 510, 275);
                    fill(0, 59, 0);
                    stroke(255, 255, 0);
                    textSize(20);
                    textFont("Courier New");
                    text("New Virus Detected!", 510, 200);





}
